### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Joui78** [Wanwire/FloxcoreXrayKit#1]
Hello. Does anyone have any idea why this error might occur?
<img width="1125" alt="Снимок экрана 2024-03-18 в 00 14 29" src="https://github.com/Wanwire/FloxcoreXrayKit/assets/85186054/a2e28911-30ea-47dc-a171-4efca523a4eb">

**Comment by tveerman** [comment]
FloxcoreXrayKit is not the same as (and is incompatible with) the XrayKit used by Mango. This Swift Package does not offer the XrayLoggerProtocol, which causes the error message you're seeing. Unfortunately, the original repository has been deleted and forks on Github only offer an old version that doesn't have the XrayLoggerProtocol as far as I can tell.

**Comment by Joui78** [comment]
> FloxcoreXrayKit is not the same as (and is incompatible with) the XrayKit used by Mango. This Swift Package does not offer the XrayLoggerProtocol, which causes the error message you're seeing. Unfortunately, the original repository has been deleted and forks on Github only offer an old version that doesn't have the XrayLoggerProtocol as far as I can tell.

Maybe you know where I can get the original XrayKit for mango?

**Comment by tveerman** [comment]
Unfortunately, no. You can search Github: https://github.com/search?q=XrayKit+fork%3Aonly+language%3ASwift&type=repositories . Through this way I found someone who appears to have been trying to implement their own XRayLoggerProtocol support: https://github.com/XTLS/libXray/issues/15 . Perhaps you can ask this person for some pointers.
