### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by laichunhui** [Wanwire/FloxcoreXrayKit#3]
When LibXray is directly integrated into the project, an error is reported.!
<img width="1014" alt="截屏2024-05-25 17 54 16" src="https://github.com/Wanwire/FloxcoreXrayKit/assets/11333652/bf107683-a3a6-4f33-8b75-874ab35ee68c">
The direct reason is this code:
`let result = libxray_main(argc, &argv, envc, &envv) `

how to fix it.

**Comment by tveerman** [comment]
The error indicates the linker is missing the _res_9_{nclose,ninit,nsearch} symbols. You need to link against libresolv.tbd in Build Phases -> Link Binary With Libraries to get them.

**Comment by laichunhui** [comment]
> The error indicates the linker is missing the _res_9_{nclose,ninit,nsearch} symbols. You need to link against libresolv.tbd in Build Phases -> Link Binary With Libraries to get them.

It's done, thank you
